name: Mazicky
description: Full-Stack Web Development & Indie Game Development
meta_description: "Full-Stack Web Development & Indie Game Development"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://mazicky.github.io'
google_analytics: 'UA-67859986-1'
disqus: true
disqus_shortname: 'mazicky'

# Details for the RSS feed generator
url:            'http://mazicky.github.io'
author:         'mazicky'
authorTwitter:  'mazicky'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
